/**
 * Public, curated suggestions for profile autocomplete, not exhaustive enumerations.
 * Custom role and location entries are always supported; these are not validation lists.
 * Keep labels static so server and client render the same suggestions in English.
 */
export const ROLE_GROUPS: Record<string, string[]> = {
  "Technology and AI": [
    "Software Engineer",
    "Frontend Engineer",
    "Backend Engineer",
    "Full Stack Developer",
    "Web Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "Game Developer",
    "Embedded Software Engineer",
    "Firmware Engineer",
    "Systems Engineer",
    "Solutions Architect",
    "Enterprise Architect",
    "Cloud Architect",
    "Cloud Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Platform Engineer",
    "Infrastructure Engineer",
    "Network Engineer",
    "Database Administrator",
    "Database Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Data Analyst",
    "Data Scientist",
    "Business Intelligence Analyst",
    "Machine Learning Engineer",
    "AI Engineer",
    "AI Research Scientist",
    "Applied Scientist",
    "NLP Engineer",
    "Computer Vision Engineer",
    "Robotics Software Engineer",
    "MLOps Engineer",
    "AI Evaluation Specialist",
    "Conversational AI Designer",
    "Data Annotation Specialist",
    "QA Engineer",
    "Software Test Engineer",
    "Test Automation Engineer",
    "Performance Engineer",
    "Security Engineer",
    "Application Security Engineer",
    "Cybersecurity Analyst",
    "Penetration Tester",
    "Security Operations Analyst",
    "Incident Response Analyst",
    "Digital Forensics Analyst",
    "IT Support Specialist",
    "Help Desk Technician",
    "Systems Administrator",
    "IT Manager",
    "Technical Support Engineer",
    "Salesforce Developer",
    "ERP Consultant",
    "SAP Consultant",
    "Blockchain Developer",
    "Developer Advocate",
    "Technical Writer",
    "Release Manager",
  ],
  "Product and Design": [
    "Product Manager",
    "Technical Product Manager",
    "Product Owner",
    "Product Analyst",
    "Product Operations Manager",
    "Product Designer",
    "UX Designer",
    "UI Designer",
    "UX Researcher",
    "Interaction Designer",
    "Service Designer",
    "Design Researcher",
    "Content Designer",
    "UX Writer",
    "Information Architect",
    "Design Systems Designer",
    "Design Operations Manager",
    "Visual Designer",
    "Graphic Designer",
    "Brand Designer",
    "Motion Designer",
    "Industrial Designer",
    "Accessibility Specialist",
    "Usability Analyst",
    "Game Designer",
    "Creative Director",
  ],
  "Sales and Marketing": [
    "Sales Representative",
    "Sales Development Representative",
    "Business Development Representative",
    "Account Executive",
    "Account Manager",
    "Key Account Manager",
    "Sales Manager",
    "Sales Engineer",
    "Solutions Consultant",
    "Presales Consultant",
    "Sales Operations Analyst",
    "Revenue Operations Manager",
    "Business Development Manager",
    "Partnerships Manager",
    "Channel Sales Manager",
    "Customer Success Manager",
    "Customer Success Specialist",
    "Customer Support Representative",
    "Customer Experience Manager",
    "Implementation Consultant",
    "Marketing Manager",
    "Digital Marketing Specialist",
    "Growth Marketing Manager",
    "Product Marketing Manager",
    "Content Marketing Manager",
    "Content Strategist",
    "Copywriter",
    "SEO Specialist",
    "Search Engine Marketing Specialist",
    "Performance Marketing Manager",
    "Social Media Manager",
    "Community Manager",
    "Email Marketing Specialist",
    "CRM Manager",
    "Marketing Operations Manager",
    "Brand Manager",
    "Public Relations Specialist",
    "Communications Manager",
    "Market Research Analyst",
    "Demand Generation Manager",
    "Event Marketing Manager",
    "Influencer Marketing Manager",
    "Affiliate Marketing Manager",
    "Media Buyer",
    "Advertising Account Planner",
  ],
  "Business, Finance and Accounting": [
    "Business Analyst",
    "Management Consultant",
    "Strategy Consultant",
    "Business Operations Analyst",
    "Corporate Strategy Manager",
    "Financial Analyst",
    "Financial Planner",
    "Financial Advisor",
    "Investment Analyst",
    "Investment Banker",
    "Equity Research Analyst",
    "Portfolio Manager",
    "Wealth Manager",
    "Credit Analyst",
    "Risk Analyst",
    "Quantitative Analyst",
    "Actuary",
    "Treasury Analyst",
    "Treasury Manager",
    "FP&A Analyst",
    "Finance Manager",
    "Financial Controller",
    "Accountant",
    "Chartered Accountant",
    "Certified Public Accountant",
    "Management Accountant",
    "Cost Accountant",
    "Tax Accountant",
    "Tax Consultant",
    "Bookkeeper",
    "Accounts Payable Specialist",
    "Accounts Receivable Specialist",
    "Payroll Specialist",
    "Auditor",
    "Internal Auditor",
    "Forensic Accountant",
    "Bank Teller",
    "Relationship Manager",
    "Loan Officer",
    "Mortgage Advisor",
    "Insurance Agent",
    "Insurance Underwriter",
    "Claims Adjuster",
    "Fraud Analyst",
    "Compliance Analyst",
    "Investor Relations Manager",
    "Corporate Development Manager",
    "Venture Capital Associate",
    "Private Equity Associate",
  ],
  "Operations, HR and Legal": [
    "Operations Manager",
    "Operations Analyst",
    "Project Manager",
    "Program Manager",
    "Technical Program Manager",
    "Project Coordinator",
    "Scrum Master",
    "Agile Coach",
    "Process Improvement Analyst",
    "Quality Assurance Manager",
    "Procurement Manager",
    "Purchasing Agent",
    "Vendor Manager",
    "Facilities Manager",
    "Office Manager",
    "Administrative Assistant",
    "Executive Assistant",
    "Receptionist",
    "Data Entry Clerk",
    "Human Resources Manager",
    "HR Business Partner",
    "HR Generalist",
    "HR Coordinator",
    "Recruiter",
    "Technical Recruiter",
    "Talent Acquisition Specialist",
    "Sourcing Specialist",
    "Compensation and Benefits Analyst",
    "Learning and Development Specialist",
    "Employee Relations Specialist",
    "People Operations Manager",
    "Workforce Planning Analyst",
    "Organizational Development Consultant",
    "Lawyer",
    "Legal Counsel",
    "Corporate Counsel",
    "Paralegal",
    "Legal Assistant",
    "Contract Manager",
    "Company Secretary",
    "Data Protection Officer",
    "Intellectual Property Specialist",
    "Legal Operations Manager",
    "Mediator",
  ],
  Healthcare: [
    "Physician",
    "General Practitioner",
    "Surgeon",
    "Pediatrician",
    "Psychiatrist",
    "Radiologist",
    "Anesthesiologist",
    "Dentist",
    "Dental Hygienist",
    "Registered Nurse",
    "Nurse Practitioner",
    "Nursing Assistant",
    "Midwife",
    "Physician Assistant",
    "Pharmacist",
    "Pharmacy Technician",
    "Physical Therapist",
    "Occupational Therapist",
    "Speech Language Pathologist",
    "Respiratory Therapist",
    "Clinical Psychologist",
    "Mental Health Counselor",
    "Dietitian",
    "Nutritionist",
    "Paramedic",
    "Emergency Medical Technician",
    "Medical Laboratory Technician",
    "Radiologic Technologist",
    "Sonographer",
    "Optometrist",
    "Optician",
    "Medical Assistant",
    "Medical Coder",
    "Medical Billing Specialist",
    "Healthcare Administrator",
    "Clinical Operations Manager",
    "Patient Care Coordinator",
    "Public Health Specialist",
    "Epidemiologist",
    "Veterinarian",
    "Veterinary Technician",
    "Home Health Aide",
  ],
  "Science, Research and Education": [
    "Research Scientist",
    "Research Assistant",
    "Laboratory Technician",
    "Laboratory Manager",
    "Biologist",
    "Microbiologist",
    "Biochemist",
    "Biotechnologist",
    "Chemist",
    "Analytical Chemist",
    "Physicist",
    "Materials Scientist",
    "Neuroscientist",
    "Geneticist",
    "Bioinformatics Scientist",
    "Clinical Research Associate",
    "Clinical Research Coordinator",
    "Clinical Data Manager",
    "Regulatory Affairs Specialist",
    "Medical Science Liaison",
    "Statistician",
    "Mathematician",
    "Economist",
    "Sociologist",
    "Anthropologist",
    "Archaeologist",
    "Geologist",
    "Oceanographer",
    "Meteorologist",
    "School Teacher",
    "Preschool Teacher",
    "Primary School Teacher",
    "Secondary School Teacher",
    "Special Education Teacher",
    "Teaching Assistant",
    "Tutor",
    "University Professor",
    "Lecturer",
    "Postdoctoral Researcher",
    "School Principal",
    "Academic Advisor",
    "School Counselor",
    "Instructional Designer",
    "Curriculum Developer",
    "Corporate Trainer",
    "Librarian",
    "Archivist",
    "Education Program Coordinator",
  ],
  "Engineering, Manufacturing, Construction and Trades": [
    "Mechanical Engineer",
    "Electrical Engineer",
    "Electronics Engineer",
    "Civil Engineer",
    "Structural Engineer",
    "Chemical Engineer",
    "Aerospace Engineer",
    "Automotive Engineer",
    "Biomedical Engineer",
    "Industrial Engineer",
    "Manufacturing Engineer",
    "Process Engineer",
    "Production Engineer",
    "Quality Engineer",
    "Reliability Engineer",
    "Maintenance Engineer",
    "Controls Engineer",
    "Automation Engineer",
    "Robotics Engineer",
    "Mechatronics Engineer",
    "Hardware Engineer",
    "VLSI Design Engineer",
    "Semiconductor Process Engineer",
    "RF Engineer",
    "Telecommunications Engineer",
    "CAD Designer",
    "Drafter",
    "Architect",
    "Landscape Architect",
    "Interior Designer",
    "Urban Planner",
    "Building Surveyor",
    "Quantity Surveyor",
    "Land Surveyor",
    "Construction Manager",
    "Site Engineer",
    "Site Supervisor",
    "Construction Estimator",
    "BIM Modeler",
    "Building Inspector",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Welder",
    "Machinist",
    "CNC Operator",
    "Tool and Die Maker",
    "HVAC Technician",
    "Automotive Mechanic",
    "Aircraft Maintenance Technician",
    "Maintenance Technician",
    "Industrial Maintenance Mechanic",
    "Millwright",
    "Sheet Metal Worker",
    "Mason",
    "Roofer",
    "Painter",
    "Heavy Equipment Operator",
    "Production Operator",
    "Assembly Technician",
    "Production Supervisor",
    "Plant Manager",
    "Safety Engineer",
    "Health and Safety Officer",
    "Quality Control Inspector",
  ],
  "Logistics, Agriculture, Energy and Environment": [
    "Supply Chain Analyst",
    "Supply Chain Manager",
    "Logistics Coordinator",
    "Logistics Manager",
    "Demand Planner",
    "Inventory Planner",
    "Inventory Manager",
    "Warehouse Manager",
    "Warehouse Associate",
    "Shipping and Receiving Clerk",
    "Freight Forwarder",
    "Customs Broker",
    "Transportation Planner",
    "Dispatcher",
    "Fleet Manager",
    "Truck Driver",
    "Delivery Driver",
    "Forklift Operator",
    "Railway Operations Controller",
    "Marine Engineer",
    "Ship Captain",
    "Seafarer",
    "Farmer",
    "Farm Manager",
    "Agronomist",
    "Agricultural Engineer",
    "Horticulturist",
    "Agricultural Extension Officer",
    "Food Scientist",
    "Food Safety Specialist",
    "Forester",
    "Fisheries Officer",
    "Energy Analyst",
    "Energy Engineer",
    "Renewable Energy Engineer",
    "Solar Installer",
    "Wind Turbine Technician",
    "Power Systems Engineer",
    "Petroleum Engineer",
    "Mining Engineer",
    "Environmental Engineer",
    "Environmental Scientist",
    "Environmental Consultant",
    "Sustainability Manager",
    "ESG Analyst",
    "Climate Analyst",
    "Conservation Scientist",
    "Wildlife Biologist",
    "Ecologist",
    "Water Resources Engineer",
    "Water Treatment Operator",
    "Waste Management Specialist",
    "GIS Analyst",
    "Remote Sensing Specialist",
  ],
  "Retail, Hospitality and Travel": [
    "Retail Sales Associate",
    "Store Manager",
    "Retail Buyer",
    "Merchandiser",
    "Visual Merchandiser",
    "E-commerce Manager",
    "E-commerce Specialist",
    "Cashier",
    "Personal Shopper",
    "Customer Service Associate",
    "Restaurant Manager",
    "Chef",
    "Sous Chef",
    "Pastry Chef",
    "Cook",
    "Baker",
    "Barista",
    "Bartender",
    "Server",
    "Sommelier",
    "Catering Manager",
    "Hotel Manager",
    "Front Desk Agent",
    "Concierge",
    "Housekeeping Supervisor",
    "Housekeeper",
    "Guest Relations Manager",
    "Revenue Manager",
    "Travel Agent",
    "Tour Guide",
    "Tour Operator",
    "Travel Coordinator",
    "Flight Attendant",
    "Airline Pilot",
    "Air Traffic Controller",
    "Airport Operations Manager",
    "Event Planner",
    "Wedding Planner",
    "Fitness Trainer",
    "Yoga Instructor",
    "Sports Coach",
    "Massage Therapist",
    "Beautician",
    "Hair Stylist",
    "Real Estate Agent",
    "Property Manager",
  ],
  "Media, Arts, Public Sector and Security": [
    "Journalist",
    "Reporter",
    "Editor",
    "Content Writer",
    "Author",
    "Translator",
    "Interpreter",
    "Photographer",
    "Videographer",
    "Video Editor",
    "Film Director",
    "Film Producer",
    "Screenwriter",
    "Production Assistant",
    "Animator",
    "3D Artist",
    "VFX Artist",
    "Illustrator",
    "Concept Artist",
    "Fine Artist",
    "Art Director",
    "Music Producer",
    "Musician",
    "Sound Engineer",
    "Audio Engineer",
    "Podcast Producer",
    "Actor",
    "Theatre Director",
    "Stage Manager",
    "Fashion Designer",
    "Textile Designer",
    "Museum Curator",
    "Public Policy Analyst",
    "Policy Advisor",
    "Government Affairs Manager",
    "Civil Servant",
    "Diplomat",
    "Public Administrator",
    "City Planner",
    "Police Officer",
    "Detective",
    "Firefighter",
    "Emergency Management Specialist",
    "Security Guard",
    "Security Manager",
    "Intelligence Analyst",
    "Military Officer",
    "Corrections Officer",
    "Border Services Officer",
  ],
  "Leadership, Nonprofit and Social Services": [
    "Founder",
    "Co-founder",
    "Entrepreneur",
    "Chief Executive Officer",
    "Chief Operating Officer",
    "Chief Financial Officer",
    "Chief Technology Officer",
    "Chief Information Officer",
    "Chief Product Officer",
    "Chief Marketing Officer",
    "Chief Revenue Officer",
    "Chief People Officer",
    "Chief Information Security Officer",
    "Chief Data Officer",
    "Chief of Staff",
    "Managing Director",
    "General Manager",
    "Engineering Manager",
    "Director of Engineering",
    "VP of Engineering",
    "Head of Product",
    "Head of Design",
    "Head of Sales",
    "Head of Marketing",
    "Executive Director",
    "Nonprofit Program Manager",
    "Fundraising Manager",
    "Development Officer",
    "Grant Writer",
    "Grants Manager",
    "Volunteer Coordinator",
    "Community Organizer",
    "Community Development Officer",
    "Social Worker",
    "Case Manager",
    "Youth Worker",
    "Family Support Worker",
    "Disability Support Worker",
    "Caregiver",
    "Rehabilitation Counselor",
    "Career Counselor",
    "Employment Specialist",
    "Humanitarian Aid Worker",
    "International Development Specialist",
    "Monitoring and Evaluation Specialist",
  ],
};

export const ROLE_SUGGESTIONS: string[] = [...new Set(Object.values(ROLE_GROUPS).flat())];

export const LOCATION_SUGGESTIONS: string[] = [
  "Remote",
  "Worldwide",
  "Remote, India",
  "Remote, Asia",
  "Remote, Europe",
  "Remote, North America",
  "Remote, Latin America",
  "Remote, Africa",
  "Remote, Oceania",
  "Bengaluru (Bangalore), India",
  "Mumbai, India",
  "New Delhi, India",
  "Delhi NCR, India",
  "Hyderabad, India",
  "Chennai, India",
  "Pune, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Gurugram (Gurgaon), India",
  "Noida, India",
  "Greater Noida, India",
  "Ghaziabad, India",
  "Faridabad, India",
  "Jaipur, India",
  "Lucknow, India",
  "Chandigarh, India",
  "Mohali, India",
  "Indore, India",
  "Bhopal, India",
  "Kochi (Cochin), India",
  "Thiruvananthapuram (Trivandrum), India",
  "Coimbatore, India",
  "Madurai, India",
  "Tiruchirappalli, India",
  "Mysuru (Mysore), India",
  "Mangaluru (Mangalore), India",
  "Visakhapatnam, India",
  "Vijayawada, India",
  "Bhubaneswar, India",
  "Cuttack, India",
  "Patna, India",
  "Ranchi, India",
  "Jamshedpur, India",
  "Guwahati, India",
  "Shillong, India",
  "Imphal, India",
  "Agartala, India",
  "Nagpur, India",
  "Nashik, India",
  "Navi Mumbai, India",
  "Thane, India",
  "Surat, India",
  "Vadodara, India",
  "Rajkot, India",
  "Gandhinagar, India",
  "Kanpur, India",
  "Varanasi, India",
  "Agra, India",
  "Prayagraj, India",
  "Meerut, India",
  "Dehradun, India",
  "Haridwar, India",
  "Shimla, India",
  "Jammu, India",
  "Srinagar, India",
  "Amritsar, India",
  "Ludhiana, India",
  "Jalandhar, India",
  "Raipur, India",
  "Jodhpur, India",
  "Udaipur, India",
  "Kota, India",
  "Panaji, Goa, India",
  "New York, NY, United States",
  "San Francisco, CA, United States",
  "San Jose, CA, United States",
  "Los Angeles, CA, United States",
  "San Diego, CA, United States",
  "Sacramento, CA, United States",
  "Seattle, WA, United States",
  "Portland, OR, United States",
  "Austin, TX, United States",
  "Dallas, TX, United States",
  "Houston, TX, United States",
  "San Antonio, TX, United States",
  "Boston, MA, United States",
  "Chicago, IL, United States",
  "Washington, DC, United States",
  "Atlanta, GA, United States",
  "Miami, FL, United States",
  "Orlando, FL, United States",
  "Tampa, FL, United States",
  "Denver, CO, United States",
  "Boulder, CO, United States",
  "Phoenix, AZ, United States",
  "Las Vegas, NV, United States",
  "Salt Lake City, UT, United States",
  "Raleigh, NC, United States",
  "Charlotte, NC, United States",
  "Philadelphia, PA, United States",
  "Pittsburgh, PA, United States",
  "Detroit, MI, United States",
  "Minneapolis, MN, United States",
  "Nashville, TN, United States",
  "Columbus, OH, United States",
  "Indianapolis, IN, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Ottawa, Canada",
  "Calgary, Canada",
  "Edmonton, Canada",
  "Waterloo, Canada",
  "Quebec City, Canada",
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "San Jose, Costa Rica",
  "Panama City, Panama",
  "Bogota, Colombia",
  "Medellin, Colombia",
  "Lima, Peru",
  "Santiago, Chile",
  "Buenos Aires, Argentina",
  "Montevideo, Uruguay",
  "Sao Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Belo Horizonte, Brazil",
  "Curitiba, Brazil",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Birmingham, United Kingdom",
  "Bristol, United Kingdom",
  "Leeds, United Kingdom",
  "Cambridge, United Kingdom",
  "Oxford, United Kingdom",
  "Edinburgh, United Kingdom",
  "Glasgow, United Kingdom",
  "Belfast, United Kingdom",
  "Cardiff, United Kingdom",
  "Dublin, Ireland",
  "Cork, Ireland",
  "Paris, France",
  "Lyon, France",
  "Toulouse, France",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Frankfurt, Germany",
  "Cologne, Germany",
  "Stuttgart, Germany",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Eindhoven, Netherlands",
  "Brussels, Belgium",
  "Luxembourg City, Luxembourg",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Basel, Switzerland",
  "Vienna, Austria",
  "Prague, Czechia",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Wroclaw, Poland",
  "Budapest, Hungary",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Belgrade, Serbia",
  "Zagreb, Croatia",
  "Ljubljana, Slovenia",
  "Bratislava, Slovakia",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Valencia, Spain",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Milan, Italy",
  "Rome, Italy",
  "Turin, Italy",
  "Athens, Greece",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Reykjavik, Iceland",
  "Tallinn, Estonia",
  "Riga, Latvia",
  "Vilnius, Lithuania",
  "Kyiv, Ukraine",
  "Lviv, Ukraine",
  "Istanbul, Turkey",
  "Ankara, Turkey",
  "Tbilisi, Georgia",
  "Yerevan, Armenia",
  "Moscow, Russia",
  "Singapore, Singapore",
  "Kuala Lumpur, Malaysia",
  "Penang, Malaysia",
  "Bangkok, Thailand",
  "Jakarta, Indonesia",
  "Bandung, Indonesia",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Da Nang, Vietnam",
  "Phnom Penh, Cambodia",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Fukuoka, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Hangzhou, China",
  "Chengdu, China",
  "Hong Kong",
  "Taipei, Taiwan",
  "Dhaka, Bangladesh",
  "Karachi, Pakistan",
  "Lahore, Pakistan",
  "Islamabad, Pakistan",
  "Colombo, Sri Lanka",
  "Kathmandu, Nepal",
  "Almaty, Kazakhstan",
  "Tashkent, Uzbekistan",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "Sharjah, United Arab Emirates",
  "Riyadh, Saudi Arabia",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",
  "Manama, Bahrain",
  "Kuwait City, Kuwait",
  "Muscat, Oman",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Amman, Jordan",
  "Beirut, Lebanon",
  "Cairo, Egypt",
  "Alexandria, Egypt",
  "Casablanca, Morocco",
  "Rabat, Morocco",
  "Tunis, Tunisia",
  "Algiers, Algeria",
  "Lagos, Nigeria",
  "Abuja, Nigeria",
  "Accra, Ghana",
  "Nairobi, Kenya",
  "Kampala, Uganda",
  "Kigali, Rwanda",
  "Addis Ababa, Ethiopia",
  "Dar es Salaam, Tanzania",
  "Dakar, Senegal",
  "Abidjan, Cote d'Ivoire",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Durban, South Africa",
  "Port Louis, Mauritius",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Canberra, Australia",
  "Auckland, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Republic of the Congo",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
