# Generated by Django 5.2.17 on 2026-10-02 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('NORMAL_APPLY', 'Normal Apply'), ('COLD_APPLY', 'Cold Apply'), ('FULL_THROTTLE', 'Full-Throttle Sprint')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ONBOARDING', 'Onboarding'), ('READY', 'Ready'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('billing_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('settings_json', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['candidate', 'status'], name='campaigns_c_candida_e69cb7_idx'), models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='campaign_version_positive')],
            },
        ),
    ]
