# Generated by Django 5.2.14 on 2026-10-02 17:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10485760)])),
                ('upload_status', models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('UPLOADED', 'Uploaded'), ('FAILED', 'Failed')], default='PENDING_UPLOAD', max_length=16)),
                ('parse_status', models.CharField(choices=[('NOT_STARTED', 'Not started')], default='NOT_STARTED', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gte', 1), ('file_size__lte', 10485760)), name='resume_file_size_valid'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='resume_version_positive')],
            },
        ),
    ]
