# Generated by Django 6.0.5 on 2026-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PARSED', 'Parsed'), ('FAILED', 'Failed'), ('UNSUPPORTED', 'Unsupported')], default='NOT_STARTED', max_length=16),
        ),
    ]
