# Generated by Django 6.0.5 on 2026-10-03 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_assigned_to'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(max_length=20000)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('LINKEDIN', 'LinkedIn'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('SENT', 'Sent'), ('REPLIED', 'Replied'), ('POSITIVE_REPLY', 'Positive reply'), ('BOUNCED', 'Bounced'), ('CLOSED', 'Closed'), ('SUPPRESSED', 'Suppressed')], default='DRAFT', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, max_length=20000)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reply_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_due_at', models.DateTimeField(blank=True, null=True)),
                ('thread_reference', models.CharField(blank=True, max_length=1000)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach', to='contacts.contact')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'indexes': [models.Index(fields=['campaign', 'status'], name='outreach_ou_campaig_829dfe_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'contact', 'channel'), name='outreach_campaign_contact_channel_unique')],
            },
        ),
    ]
