# Generated by Django 6.0.5 on 2026-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('TARGET_IDENTIFIED', 'Target identified'), ('CONTACT_VERIFIED', 'Contact verified'), ('DRAFTED', 'Drafted'), ('REVIEW_REQUIRED', 'Review required'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('REPLIED', 'Replied'), ('POSITIVE_REPLY', 'Positive reply'), ('NEGATIVE_REPLY', 'Negative reply'), ('BOUNCED', 'Bounced'), ('CLOSED', 'Closed'), ('SUPPRESSED', 'Suppressed')], default='DRAFT', max_length=20),
        ),
    ]
