# Generated by Django 6.0.5 on 2026-10-03 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.CharField(choices=[('profile_extract', 'Profile Extract'), ('job_match', 'Job Match'), ('outreach_draft', 'Outreach Draft'), ('qa', 'Qa')], max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='QUEUED', max_length=16)),
                ('input_json', models.JSONField(default=dict)),
                ('result', models.JSONField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('provider_request_id', models.CharField(blank=True, max_length=128)),
                ('usage_json', models.JSONField(default=dict)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_runs', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
