# Generated by Django 5.2

import apps.candidates.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "experience_summary",
                    models.TextField(blank=True, max_length=5000),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        default=list,
                        validators=[apps.candidates.models.validate_profile_list],
                    ),
                ),
                (
                    "preferred_locations",
                    models.JSONField(
                        default=list,
                        validators=[apps.candidates.models.validate_profile_list],
                    ),
                ),
                (
                    "remote_preference",
                    models.CharField(
                        choices=[
                            ("UNSPECIFIED", "Unspecified"),
                            ("ONSITE", "Onsite"),
                            ("HYBRID", "Hybrid"),
                            ("REMOTE", "Remote"),
                            ("FLEXIBLE", "Flexible"),
                        ],
                        default="UNSPECIFIED",
                        max_length=12,
                    ),
                ),
                ("profile_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(profile_version__gte=1),
                        name="candidate_profile_version_positive",
                    ),
                ],
            },
        ),
    ]
