# Generated by Django 6.0.5 on 2026-10-03 06:47

import apps.candidates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_ctc_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_ctc_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='notice_period',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferences_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='review_notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested')], default='PENDING', max_length=24),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='sponsorship_requirement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='target_industries',
            field=models.JSONField(default=list, validators=[apps.candidates.models.validate_profile_list]),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_authorization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
