# Generated by Django 6.0.5 on 2026-10-03 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_expected_ctc_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidateprofile',
            constraint=models.CheckConstraint(condition=models.Q(('expected_ctc_min__isnull', True), ('expected_ctc_min__gte', 0), _connector='OR'), name='candidate_ctc_min_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='candidateprofile',
            constraint=models.CheckConstraint(condition=models.Q(('expected_ctc_max__isnull', True), ('expected_ctc_max__gte', 0), _connector='OR'), name='candidate_ctc_max_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='candidateprofile',
            constraint=models.CheckConstraint(condition=models.Q(('expected_ctc_min__isnull', True), ('expected_ctc_max__isnull', True), ('expected_ctc_max__gte', models.F('expected_ctc_min')), _connector='OR'), name='candidate_ctc_ordered'),
        ),
    ]
