# Generated by Django 6.0.5 on 2026-10-03 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('canonical_url', models.URLField(blank=True, max_length=1000)),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=250)),
                ('identity_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=30000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('canonical_url', ''), _negated=True), fields=('canonical_url',), name='job_canonical_url_unique'), models.UniqueConstraint(condition=models.Q(models.Q(('external_source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('external_source', 'external_id'), name='job_source_id_unique')],
            },
        ),
    ]
