# Generated by Django 6.0.5 on 2026-10-03 06:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_campaign_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16)),
                ('payload_json', models.JSONField(default=dict)),
                ('completion_notes', models.TextField(blank=True, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_tasks', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_tasks', to='campaigns.campaign')),
            ],
            options={
                'ordering': ('priority', 'created_at', 'id'),
                'indexes': [models.Index(fields=['campaign', 'status'], name='tasks_human_campaig_2edfcc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority__gte', 1), ('priority__lte', 5)), name='task_priority_range')],
            },
        ),
    ]
