# Generated by Django 5.2.17 on 2026-10-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(choices=[
                    ("DISCOVERED", "Discovered"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("QUEUED", "Queued"),
                    ("IN_PROGRESS", "In progress"),
                    ("SUBMITTED", "Submitted"),
                    ("APPLICATION_FAILED", "Application failed"),
                    ("IN_REVIEW", "In review"),
                    ("RECRUITER_CONTACTED", "Recruiter contacted"),
                    ("INTERVIEW", "Interview"),
                    ("INTERVIEW_SCHEDULED", "Interview scheduled"),
                    ("OFFER", "Offer"),
                    ("REJECTED", "Rejected"),
                ], default="DISCOVERED", max_length=24)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("source_reference", models.CharField(blank=True, max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="campaigns.campaign")),
                ("candidate", models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="candidates.candidateprofile")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applications", to="jobs.job")),
                ("operator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="managed_applications", to="users.user")),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["campaign", "status"], name="application_campaig_a88536_idx"),
                    models.Index(fields=["status", "created_at"], name="application_status_413525_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("candidate", "job"), name="applications_candidate_job_unique"),
                ],
            },
        ),
    ]
