# Generated by Django 6.0.5 on 2026-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_candidate_dedup'),
        ('campaigns', '0002_campaign_assigned_to'),
        ('candidates', '0003_candidateprofile_candidate_ctc_min_nonnegative_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='failure_reason',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='application',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('READY', 'Ready'), ('DISCOVERED', 'Discovered'), ('SHORTLISTED', 'Shortlisted'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('APPLICATION_FAILED', 'Application failed'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('RECRUITER_CONTACTED', 'Recruiter contacted'), ('INTERVIEW', 'Interview'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SAVED', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'INTERVIEW_SCHEDULED'), _negated=True), ('interview_scheduled_at__isnull', False), _connector='OR'), name='application_interview_date_required'),
        ),
    ]
